@startuml
actor Admin
boundary list_blogs_view
boundary detail_blogs_view
control BlogController
entity BlogModel

activate Admin
Admin -> list_blogs_view: yêu cầu xem danh sách bài viết
activate list_blogs_view
Admin <-- list_blogs_view: Hiển thị danh sách bài viết
Admin -> list_blogs_view: Bấm vào bài viết
deactivate Admin
list_blogs_view-> detail_blogs_view: chuyển tới trang chi tiết bài viết
deactivate list_blogs_view
activate detail_blogs_view
detail_blogs_view ->BlogController:yêu cầu lấy dữ liệu
activate BlogController
BlogController -> BlogController : kiểm tra dữ liệu
BlogController -> BlogModel : lấy dữ liệu
activate BlogModel
BlogModel --> BlogController : trả dữ liệu bài viết
deactivate BlogModel
detail_blogs_view<-- BlogController : trả kết qủa xóa bài viết
deactivate BlogController
Admin <-- detail_blogs_view:hiển thị nội dung bài viết
activate Admin
deactivate detail_blogs_view
deactivate Admin

@enduml