@startuml
actor Admin
boundary list_categories_view
control CategoryController
entity CategoryModel

Admin -> list_categories_view : yêu cầu xem danh sách danh mục
activate Admin
activate list_categories_view
list_categories_view -> CategoryController: gửi yêu cầu
deactivate list_categories_view
activate CategoryController
CategoryController -> CategoryController : kiểm tra dữ liệu
CategoryController -> CategoryModel : lấy danh sách danh mục
activate CategoryModel
CategoryModel --> CategoryController : trả danh sách danh mục
deactivate CategoryModel
CategoryController --> list_categories_view: trả kết qủa danh sách danh mục
deactivate CategoryController
activate list_categories_view
list_categories_view --> Admin: Hiển thị danh sách danh mục
deactivate list_categories_view
deactivate Admin

@enduml