@startuml
|Admin|
start
:Tạo quảng cáo mới;
|Hệ thống|
:Yêu cầu nhập thông tin quảng cáo;
|Admin|
:Nhập thông tin;
|Hệ thống|
:Xử lý;
if (Kiểm tra thông tin) then ( hợp lệ)
:Lưu quảng cáo mới;
stop
else (không hợp lệ)
:Hiển thị thông báo lỗi;
stop
endiftu
@enduml