@startuml
|Admin|
start
:Tạo mã giảm giá mới;
|Hệ thống|
:Yêu cầu nhập thông tin mã giảm giá;
|Admin|
repeat
|Admin|
:Nhập thông tin;
|Hệ thống|
:Xử lý;
repeat while(Kiểm tra thông tin) is (không hợp lệ)
|Hệ thống|
:Lưu mã giảm giá mới;
stop

@enduml