@startuml
|Admin|
start
:Chọn sản phẩm muốn xóa;
|Hệ thống|
if (Kiểm tra sản phẩm) then (tốn tại)
|Admin|
if (Xác nhận xóa) then (đồng ý)
|Hệ thống|
:Xóa sản phẩm;
else (không đồng ý)
|Admin|
stop
endif
else (không tồn tại)
|Hệ thống|
:Báo lỗi không tồn tại;
stop
endif

stop

@enduml