@startuml
|Admin|
start
:Chọn sản phẩm cần sửa;
|Hệ thống|
if (Kiểm tra sản phẩm) then (tốn tại)
|Hệ thống|
:Hiển thị thông tin sản phẩm;
|Admin|
repeat
|Admin|
:Sửa thông tin;
:Bấm nút lưu;
|Hệ thống|
:Xử lý;
repeat while(Kiểm tra thông tin) is (không hợp lệ)
|Hệ thống|
:Lưu sản phẩm;
stop

else (không tồn tại)
|Hệ thống|
:Báo lỗi không tồn tại;
stop
endif

@enduml